server:
  port: 10003

spring:
  application:
    name: social-service

  neo4j:
    authentication:
      username: ${SOCIAL_DB_USERNAME}
      password: ${SOCIAL_DB_PASSWORD}
    uri: ${SOCIAL_DB_URI}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

grpc:
  server:
    port: 11003

passport:
  key: ${PASSPORT_KEY}
  algorithm: ${PASSPORT_ALGORITHM}

eureka:
  instance:
    hostname: 52.78.82.226:8761
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://52.78.82.226:8761/eureka
