server:
  port: 10003

spring:
  application:
    name: social-service

  neo4j:
    authentication:
      username: ${SOCIAL_DB_USERNAME}
      password: ${SOCIAL_DB_PASSWORD}
    uri: ${SOCIAL_DB_URI}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    consumer:
      group-id: timeline-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka

grpc:
  server:
    port: 11003

passport:
  key: ${PASSPORT_KEY}
  algorithm: ${PASSPORT_ALGORITHM}
