docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md', '**/*.pdf']

config:
  - changed-files:
      - any-glob-to-any-file: 'config/**'
  - head-branch: ['^config', 'config']

script:
  - changed-files:
      - any-glob-to-any-file: 'scripts/**'

android:
  - changed-files:
      - any-glob-to-any-file: 'src/mobile/**'

web:
  - changed-files:
      - any-glob-to-any-file: 'src/web/**'

server:
  - changed-files:
      - any-glob-to-any-file: 'src/*-service/**'

feature:
  - head-branch: ['^feat', 'feat', '^feature', 'feature']

refactor:
  - head-branch: ['^refactor', 'refactor']

fix:
  - head-branch: ['^fix', 'fix']
