server:
  port: 10004

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${USER_DB_URI}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_size: 999
        show_sql: true
        format_sql: true
        use-new-id-generator-mappings: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

grpc:
  server:
    port: 11004
  client:
    social-service:
      address: 'discovery:///SOCIAL-SERVICE'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    auth-service:
      address: 'discovery:///AUTH-SERVICE'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

passport:
  key: ${PASSPORT_KEY}
  algorithm: ${PASSPORT_ALGORITHM}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
