server:
  port: 10004

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${USER_DB_URI}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_size: 999
        show_sql: true
        format_sql: true
        use-new-id-generator-mappings: false

grpc:
  server:
    port: 11004
  client:
    social-service:
      address: 'discovery:///SOCIAL-SERVICE'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    auth-service:
      address: 'discovery:///AUTH-SERVICE'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

passport:
  key: ${PASSPORT_KEY}
  algorithm: ${PASSPORT_ALGORITHM}

eureka:
  instance:
    hostname: 15.164.88.57
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://15.164.88.57:8761/eureka
