server:
  port: 10005

spring:
  application:
    name: timeline-service

  data:
    redis:
      host: ${TIMELINE_REDIS_HOST}
      port: ${TIMELINE_REDIS_PORT}

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
