server:
  port: 10005

spring:
  application:
    name: timeline-service

  data:
    redis:
      host: ${TIMELINE_REDIS_HOST}
      port: ${TIMELINE_REDIS_PORT}
      password: ${TIMELINE_REDIS_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    consumer:
      group-id: timeline-consumer-group
      auto-offset-reset: earliest

grpc:
  server:
    port: 11005
  client:
    social-service:
      address: 'discovery:///SOCIAL-SERVICE'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

passport:
  key: ${PASSPORT_KEY}
  algorithm: ${PASSPORT_ALGORITHM}

eureka:
  instance:
    hostname: 15.164.88.57
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://15.164.88.57:8761/eureka
