server:
  port: 10001

spring:
  application:
    name: auth-service
  mail:
    host: ${AUTH_MAIL_HOST}
    username: ${AUTH_MAIL_USERNAME}
    password: ${AUTH_MAIL_PASSWORD}
    port: ${AUTH_MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
  data:
    redis:
      host: ${AUTH_REDIS_HOST}
      port: ${AUTH_REDIS_PORT}

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

grpc:
  server:
    port: 11001
  client:
    social-service:
      address: 'discovery:///AUTH-SERVICE'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
