FROM openjdk:17-oracle

ENV AUTH_MAIL_HOST=${AUTH_MAIL_HOST}
ENV AUTH_MAIL_ADDRESS=${AUTH_MAIL_ADDRESS}
ENV AUTH_MAIL_USERNAME=${AUTH_MAIL_USERNAME}
ENV AUTH_MAIL_PASSWORD=${AUTH_MAIL_PASSWORD}
ENV AUTH_MAIL_PORT=${AUTH_MAIL_PORT}
ENV AUTH_REDIS_HOST=${AUTH_REDIS_HOST}
ENV AUTH_REDIS_PORT=${AUTH_REDIS_PORT}
ENV AUTH_JWT_SECRET_KEY=${AUTH_JWT_SECRET_KEY}
ENV PASSPORT_KEY=${PASSPORT_KEY}
ENV PASSPORT_KEY=${PASSPORT_KEY}

ARG JAR_FILE=build/libs/easel-auth-service-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} easel-auth-service.jar
ENTRYPOINT ["java", "-jar", "/easel-auth-service.jar"]
