version: '3'

services:
  discovery:
    image: palette1203/discovery-service
    ports:
      - "8761:8761"
    restart: always

  auth:
    image: palette1203/auth-service
    ports:
      - "8086:8086"
    restart: always
    depends_on:
      - discovery

  user:
    image: palette1203/user-service
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - discovery

  gateway:
    image: palette1203/gateway-service
    ports:
      - "8084:8084"
    restart: always
    depends_on:
      - discovery

