version: '3'

services:
  dm:
    image: palette1203/dm-service
    ports:
      - "8081:8081"
    restart: always

  user:
    image: palette1203/user-service
    ports:
      - "8082:8082"
    restart: always

  timeline:
    image: palette1203/timeline-service
    ports:
      - "8083:8083"
    restart: always

  gateway:
    image: palette1203/gateway-service
    ports:
      - "8084:8084"
    restart: always

  notification:
    image: palette1203/notification-service
    ports:
      - "8085:8085"
    restart: always

  auth:
    image: palette1203/auth-service
    ports:
      - "8086:8086"
    restart: always

  discovery:
    image: palette1203/discovery-service
    ports:
      - "8761:8761"
    restart: always

  social:
    image: palette1203/social-service
    ports:
      - "8087:8087"
    restart: always
