.PHONY: up down all

all: up

up:
	docker-compose up -d

down:
	docker-compose down

up-user:
	docker-compose -f docker-compose-user.yml up -d

down-user:
	docker-compose -f docker-compose-user.yml down
