name: Easel UserService CI/CD with Gradle, Github Actions

on:
  push:
    branches: [ "user/dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: 빌드 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: 프로젝트 빌드
        run: ./gradlew clean build -x test
        shell: bash

      - name: API 빌드 파일 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: "src/user-service/build/libs/easel-user-service-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu"

      - name: API LIGHTSAIL 인스턴스 접속 및 애플리케이션 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            sudo cd /home/ubuntu
            sudo fuser -k 10004/tcp
            sudo ./operate.sh
