name: web-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/web/**'

jobs:
  web-ci-action:
    name: ci actions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/web

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: './src/web'

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: check lint
        run: pnpm lint

      - name: check type
        run: pnpm type:check

      - name: check testing
        run: pnpm test

      - name: check build
        run: pnpm build
